import axios, { type AxiosInstance } from "axios";

import type { AppConfig } from "../config.js";
import type { PullRequestInfo, ValidationResult } from "../types.js";

export class GitHubService {
  private readonly client: AxiosInstance;

  constructor(private readonly config: AppConfig) {
    this.client = axios.create({
      baseURL: config.GITHUB_API_BASE_URL,
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${config.GITHUB_TOKEN}`,
        "X-GitHub-Api-Version": "2022-11-28"
      },
      timeout: 30000
    });
  }

  async createDraftPullRequest(input: {
    branchName: string;
    title: string;
    ticketKey: string;
    ticketUrl: string;
    summaryOfChanges: string;
    validation: ValidationResult;
  }): Promise<PullRequestInfo> {
    const body = buildPullRequestBody(input);
    const response = await this.client.post<{
      number: number;
      html_url: string;
    }>(`/repos/${this.config.GITHUB_OWNER}/${this.config.GITHUB_REPO}/pulls`, {
      title: input.title,
      head: input.branchName,
      base: this.config.GIT_BASE_BRANCH,
      body,
      draft: true
    });

    return {
      number: response.data.number,
      url: response.data.html_url
    };
  }
}

function buildPullRequestBody(input: {
  branchName: string;
  title: string;
  ticketKey: string;
  ticketUrl: string;
  summaryOfChanges: string;
  validation: ValidationResult;
}): string {
  const validationSteps = input.validation.steps
    .map((step) => `- ${step.command}: ${step.success ? "passed" : "failed"}`)
    .join("\n");

  return [
    `Jira ticket: [${input.ticketKey}](${input.ticketUrl})`,
    "",
    "Summary of changes:",
    input.summaryOfChanges,
    "",
    "Validation steps run:",
    validationSteps,
    "",
    "Note: This pull request was generated by an AI coding worker and is intentionally opened as a draft for human review."
  ].join("\n");
}
