import axios, { type AxiosInstance } from "axios";

import type { AppConfig } from "../config.js";
import type { PullRequestInfo, ValidationResult } from "../types.js";
import { Logger } from "../utils/logger.js";

export class GitHubService {
  private readonly client: AxiosInstance;
  private readonly logger = new Logger("github");

  constructor(private readonly config: AppConfig) {
    this.client = axios.create({
      baseURL: config.GITHUB_API_BASE_URL,
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${config.GITHUB_TOKEN}`,
        "X-GitHub-Api-Version": "2022-11-28"
      },
      timeout: 30000
    });
  }

  async resolveUniquePullRequestTitle(ticketKey: string, summary: string): Promise<string> {
    const baseTitle = `${ticketKey}: ${summary}`;
    const existingTitles = await this.listExistingPullRequestTitles(ticketKey);

    if (!existingTitles.has(baseTitle)) {
      return baseTitle;
    }

    for (let version = 1; version < 1000; version += 1) {
      const candidate = `${baseTitle} _v${version}`;
      if (!existingTitles.has(candidate)) {
        this.logger.warn("Base PR title already exists; using versioned PR title", {
          baseTitle,
          candidate
        });
        return candidate;
      }
    }

    throw new Error(`Unable to find a unique PR title for ${baseTitle}`);
  }

  async createDraftPullRequest(input: {
    branchName: string;
    title: string;
    ticketKey: string;
    ticketUrl: string;
    summaryOfChanges: string;
    validation: ValidationResult;
  }): Promise<PullRequestInfo> {
    this.logger.info("Creating draft GitHub pull request", {
      owner: this.config.GITHUB_OWNER,
      repo: this.config.GITHUB_REPO,
      branchName: input.branchName,
      baseBranch: this.config.GIT_BASE_BRANCH
    });

    const body = buildPullRequestBody(input);
    const response = await this.client.post<{
      number: number;
      html_url: string;
    }>(`/repos/${this.config.GITHUB_OWNER}/${this.config.GITHUB_REPO}/pulls`, {
      title: input.title,
      head: input.branchName,
      base: this.config.GIT_BASE_BRANCH,
      body,
      draft: true
    });

    this.logger.info("Draft pull request created", {
      number: response.data.number,
      url: response.data.html_url
    });

    return {
      number: response.data.number,
      url: response.data.html_url
    };
  }

  private async listExistingPullRequestTitles(ticketKey: string): Promise<Set<string>> {
    const response = await this.client.get<
      Array<{
        title: string;
      }>
    >(`/repos/${this.config.GITHUB_OWNER}/${this.config.GITHUB_REPO}/pulls`, {
      params: {
        state: "all",
        per_page: 100
      }
    });

    return new Set(
      response.data
        .map((pullRequest) => pullRequest.title.trim())
        .filter((title) => title.startsWith(`${ticketKey}: `))
    );
  }
}

function buildPullRequestBody(input: {
  branchName: string;
  title: string;
  ticketKey: string;
  ticketUrl: string;
  summaryOfChanges: string;
  validation: ValidationResult;
}): string {
  const validationSteps = input.validation.steps
    .map((step) => `- ${step.command}: ${step.success ? "passed" : "failed"}`)
    .join("\n");

  return [
    `Jira ticket: [${input.ticketKey}](${input.ticketUrl})`,
    "",
    "Summary of changes:",
    input.summaryOfChanges,
    "",
    "Validation steps run:",
    validationSteps,
    "",
    "Note: This pull request was generated by an AI coding worker and is intentionally opened as a draft for human review."
  ].join("\n");
}
